### ISSUE TITLE
compilation error 

### ISSUE THREAD

**Issue by JanickRoss** [preboot/angular2-library-seed#1]
When I build project with npm start or npm build, I have this error :
![compilation_error](https://cloud.githubusercontent.com/assets/1583726/14825264/27049aa4-0ba7-11e6-918e-b61c6cf0e5f7.png)

**Comment by NathanWalker** [comment]
Hi @JanickRoss I just pushed up compatibility with the newly release beta.16. 
And also a fix for your issue. Please pull latest and try it... reopen if you still see it, thanks!
