### ISSUE TITLE
Question about publishing

### ISSUE THREAD

**Issue by dions00** [preboot/angular2-library-seed#13]
I'm trying to test the publish of a library.  When I use 'npm pack', the ng2-your-library-0.0.0.tgz file doesn't contain any javascript or d.ts files

Can you explain to me what I should put inside the package.json? I tried:   
 ...
  "main": "ng2-your-library",
  "typings": "index.d.ts",
...
What are the files the tgz file will have,  the contain of the dist folder?

Thanks,
Stephane

**Comment by stratus1011** [comment]
I am wondering the same thing. I'm not sure how to generate the actual library files and package them

**Comment by gabwh** [comment]
+1

**Comment by NathanWalker** [comment]
Hi @dions00 @gabwh @stratus1011 sorry for late response; you don't need to use `npm pack` for publishing. Instead, please follow these instructions to publish (new simpler publishing prep steps):
https://github.com/preboot/angular-library-seed/blob/master/PUBLISHING.md

Repo was just updated to use new `ngx` prefix; also dependencies were updated.

**Comment by NathanWalker** [comment]
There's a couple other things I want to add to make this a bit nicer, please refer to this issue:
https://github.com/preboot/angular-library-seed/issues/10
mainly outputting a UMD bundle.

/cc @shlomiassaf  thanks for tips there - will look at your resources - if you get a chance or have any interest in submitting a PR to add support for UMD bundling would be greatly appreciated.
