### ISSUE TITLE
prepublish error 

### ISSUE THREAD

**Issue by JanickRoss** [preboot/angular2-library-seed#2]
I have now an error when I try to prepublish because it search \src\app\components\sample.scss.js:

![compilation_error](https://cloud.githubusercontent.com/assets/1583726/14833225/31769436-0bcc-11e6-952a-936fa25573b8.png)

**Comment by NathanWalker** [comment]
for now, don't use `make.js`... I'll update the docs soon for that. In meantime, just use:

```
tsc
```

to build. And actually don't add a `prepublish` script to `package.json`... Just run that manually before publishing (without a prepublish) script.

I'll cc @jkuri here and see if he could provide latest details on bundling 3rd party libs for angular cli. I believe much has changed in regards to that lately.

**Comment by jkuri** [comment]
Yes, `make.js` is deprecated. Actually 3rd party lib bundles are not needed anymore. You can find more information how to get 3rd party lib working with angular-cli [here](https://github.com/angular/angular-cli/wiki/3rd-party-libs).
