### ISSUE TITLE
Update to RC

### ISSUE THREAD

**Issue by alexcastillo** [preboot/angular2-library-seed#3]
Hey, great project!

Any plans to upgrade to RC soon?

Alex

**Comment by NathanWalker** [comment]
Thx for the ping. I'll try to take care of this in next day.

**Comment by alexcastillo** [comment]
Thank you! I'll use this for my next library.

**Comment by NathanWalker** [comment]
`master` is updated to rc.1 now 👍

**Comment by NathanWalker** [comment]
Good luck on the lib and please let us know when you get it ready!

**Comment by alexcastillo** [comment]
Will do, thank you!
