### ISSUE TITLE
Library published

### ISSUE THREAD

**Issue by alexcastillo** [preboot/angular2-library-seed#4]
Hey @NathanWalker!

Thanks for upgrading your library seed to Angular RC.
As promised, here's the library I built using your seed:

https://github.com/alexcastillo/ng2-notifications
https://www.npmjs.com/package/ng2-notifications

Do you have any feedback?

Thanks!

**Comment by NathanWalker** [comment]
@alexcastillo Your plugin looks nice. Sry for long delayed reply. Just updated this seed to Angular 2 Final 👍
