### ISSUE TITLE
Publishing new version

### ISSUE THREAD

**Issue by alexcastillo** [preboot/angular2-library-seed#5]
Hi @NathanWalker,

I've been constantly publishing new version to npm.
I was wondering if there is a better way other than editing the package.json and tsconfig.json and then reverting to the old versions.

Thanks!

Alex

**Comment by NathanWalker** [comment]
There's some potential to write a node script to help here.
Something similar was done here:
https://github.com/NathanWalker/nativescript-ng2-plugin-seed/pull/3

**Comment by NathanWalker** [comment]
@alexcastillo a publishing workflow has been added, see this:
https://github.com/preboot/angular2-library-seed/blob/master/PUBLISHING.md
